export enum VoteStatus {
    SUCCESS = 0,
    CONTINUE,
    CLOUDFLARE_FAIL,
    LOGIN_FAIL,
    ALREADY_VOTED_FAIL,
    CAPTCHA_FAIL,
    DISCORD_NEW_LOCATION_FAIL,
    FAILED_TO_CLEAR_LOGIN_DATA_FAIL,
    VOTE_TIMEOUT_FAIL,
    OTHER_CRIT_FAIL,
    OTHER_RETRY_FAIL
}